substitutions:
  # ESP32-WROOM safe pins (avoid GPIO6-11 flash pins)
  uart_dummy_tx: GPIO21
  uart_tx: GPIO17
  uart_rx: GPIO16
  modbus_id: modbus1

external_components:
  - source: github://adoublearonn/resideo@main
    components: [ irda_uart ]

uart:
  - id: rx_uart
    tx_pin: $uart_dummy_tx
    rx_pin: $uart_rx
    baud_rate: 2400
    debug:
      direction: TX
      after:
        timeout: 1ms
      sequence:
        # Forward all outbound traffic to a TX UART
        - lambda: |-
            if (!bytes.empty())
              id(tx_uart).write_array(bytes.data(), bytes.size());

  - id: tx_uart
    tx_pin: $uart_tx
    baud_rate: 2400
    debug:
      direction: TX
      after:
        timeout: 1ms

# Enables appropriate IRDA register settings
irda_uart:
  - uart_id: rx_uart
    tx_en: false
    invert: false
  - uart_id: tx_uart
    tx_en: true
    invert: true

modbus:
  uart_id: rx_uart
  id: $modbus_id
